### ISSUE TITLE
陷阵BUG

### ISSUE THREAD

**Issue by Gaeric** [donle/sgs#131]
陷阵：出牌阶段限一次，你可以与一名角色拼点，若你：赢，此阶段内你无视其防具，对其使用牌无距离和次数限制，且当你使用【杀】或普通锦囊牌仅指定唯一目标时，可令其成为目标；没赢，你本回合内不能使用【杀】且你的【杀】不计入手牌上限。

BUG：拼点没赢时杀无法弃置，但是计入手牌上限；
对局：斗地主

**Comment by Gaeric** [comment]
可能由我的另一个手牌BUG所引发，如未复现请暂勿关闭

**Comment by donle** [comment]
resolved in https://github.com/donle/sgs/commit/f094bca159e404ebcaf04f3dd5ba51ec12cfcfed
