### ISSUE TITLE
木牛流马BUG

### ISSUE THREAD

**Issue by Gaeric** [donle/sgs#149]
装备区的木牛流马中有数张牌，当其被弃置时，其区域中的牌置入弃牌堆；

当玩家再次摸到此前因此方式进入弃牌堆的牌时，牌的下方有木流牛马标记；使用此牌时，读条消失，疑似游戏已崩溃；

游戏方式：2人身份
游戏武将：主：黄忠， 反：曹植
相关卡牌：木牛流马中存放的藤甲

**Comment by xiaomo-li** [comment]
done.
