### ISSUE TITLE
Bug Record 2021/02/16

### ISSUE THREAD

**Issue by doublebit015** [donle/sgs#154]
- [x] 1. 手牌上限突破体力上限
    - 模式：斗地主
    - 出现条件：未知
    - 参考线索：程普（一号位）、周泰（二号位，不屈牌 x 1）、潘马（三号位，阵亡）

- [x] 2. 【杀】的目标不为潘马，却会询问夺刀
    - 模式：斗地主

- [x] 3. 界李儒顺了荀彧木牛，结束不触发绝策
    - 模式：斗地主

- [x] 4. 【闪电】生效后，弃置弃牌堆的日志没有显示牌名
    - 模式：斗地主

- [x] 5.  虞翻”直言“描述，”其他角色“应改为”一名角色“

**Comment by donle** [comment]
fixed 2.3 and 5 in https://github.com/donle/sgs/commit/f094bca159e404ebcaf04f3dd5ba51ec12cfcfed
